-- MySQL Script generated by MySQL Workbench
-- Mon Oct 28 14:06:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GestorBebidas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GestorBebidas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GestorBebidas` DEFAULT CHARACTER SET utf8 ;
USE `GestorBebidas` ;

-- -----------------------------------------------------
-- Table `GestorBebidas`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestorBebidas`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomCliente` VARCHAR(45) NOT NULL,
  `emailCliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestorBebidas`.`Bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestorBebidas`.`Bebida` (
  `idBebidas` INT NOT NULL AUTO_INCREMENT,
  `cantBebidas` INT NOT NULL,
  `tipoBebidas` VARCHAR(45) NOT NULL,
  `nomBebida` VARCHAR(45) NOT NULL,
  `fechaCompra` DATETIME NOT NULL,
  PRIMARY KEY (`idBebidas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestorBebidas`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestorBebidas`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `ingredienteEstado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestorBebidas`.`Recibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestorBebidas`.`Recibo` (
  `idRecibo` INT NOT NULL AUTO_INCREMENT,
  `tipoRecibo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRecibo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestorBebidas`.`Metodos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestorBebidas`.`Metodos` (
  `idMetodos` INT NOT NULL AUTO_INCREMENT,
  `metodosPago` VARCHAR(45) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Recibo_idRecibo` INT NOT NULL,
  PRIMARY KEY (`idMetodos`, `Cliente_idCliente`, `Recibo_idRecibo`),
  INDEX `fk_Metodos_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Metodos_Recibo1_idx` (`Recibo_idRecibo` ASC) VISIBLE,
  CONSTRAINT `fk_Metodos_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `GestorBebidas`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Metodos_Recibo1`
    FOREIGN KEY (`Recibo_idRecibo`)
    REFERENCES `GestorBebidas`.`Recibo` (`idRecibo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestorBebidas`.`Cliente_has_Bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestorBebidas`.`Cliente_has_Bebida` (
  `Cliente_idCliente` INT NOT NULL,
  `Bebida_idBebidas` INT NOT NULL,
  PRIMARY KEY (`Cliente_idCliente`, `Bebida_idBebidas`),
  INDEX `fk_Cliente_has_Bebida_Bebida1_idx` (`Bebida_idBebidas` ASC) VISIBLE,
  INDEX `fk_Cliente_has_Bebida_Cliente_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_Bebida_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `GestorBebidas`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Bebida_Bebida1`
    FOREIGN KEY (`Bebida_idBebidas`)
    REFERENCES `GestorBebidas`.`Bebida` (`idBebidas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
